export const LOTTO_ERROR_TYPES = {
  MAX_COUNT: "MAX_COUNT", INVALID_NUMBER: "INVALID_NUMBER", DUPLICATE: "DUPLICATE",
};

export const LOTTO_ERROR_MESSAGE = {
  [LOTTO_ERROR_TYPES.MAX_COUNT]: "[ERROR] 로또 번호는 6개여야 합니다.",
  [LOTTO_ERROR_TYPES.INVALID_NUMBER]: "[ERROR] 로또 번호는 1부터 45 사이의 숫자여야 합니다.",
  [LOTTO_ERROR_TYPES.DUPLICATE]: "[ERROR] 중복된 숫자가 존재합니다.",
};

export const AMOUNT_ERROR_TYPES = {
  INVALID_AMOUNT: "INVALID_AMOUNT",
  INVALID_AMOUNT_ARANGE: "INVALID_AMOUNT_ARANGE",
  INVALID_AMOUNT_FORMAT: "INVALID_AMOUNT_FORMAT",
};

export const AMOUNT_ERROR_MESSAGE = {
  [AMOUNT_ERROR_TYPES.INVALID_AMOUNT]: "[ERROR] 올바르지 않은 금액 입력입니다.",
  [AMOUNT_ERROR_TYPES.INVALID_AMOUNT_ARANGE]: "[ERROR] 로또 구입 금액은 1,000원 이상 1,000,000원 이하입니다.",
  [AMOUNT_ERROR_TYPES.INVALID_AMOUNT_FORMAT]: "[ERROR] 로도 구입 금액은 1,000원 단위 입니다.",
};
