export const LOTTO_ERROR_TYPES = {
  MAX_COUNT: "MAX_COUNT",
  INVALID_NUMBER: "INVALID_NUMBER",
  DUPLICATE: "DUPLICATE",
};

export const LOTTO_ERROR_MESSAGE = {
  [LOTTO_ERROR_TYPES.MAX_COUNT]: "[ERROR] 로또 번호는 6개여야 합니다.",
  [LOTTO_ERROR_TYPES.INVALID_NUMBER]: "[ERROR] 로또 번호는 1부터 45 사이의 숫자여야 합니다.",
  [LOTTO_ERROR_TYPES.DUPLICATE]: "[ERROR] 로또 번호는 1부터 45 사이의 숫자여야 합니다.",
};
